
// objetos literales y arrays
// Arrays es un conjunto de elementos

let empleados = ['carro','azul',1,2,3];
let DeMasEmpleados = ['Luis','Echagarreta','Yamilth'];

console.log(empleados);
console.log(empleados[0][1]);
empleados.push('luis');
console.log(empleados);
//concatenar arreglos



// stackoverflow para problemas de sitaxis.

//objetos es una coleccion de datos

let Datos = {
Nombre: 'Carlos',
Apellido: 'Echagarreta',
Edad: 36,
Nacimiento: 1985,
};

console.log(Datos);



