alert("coco");

var letra = "m";
let numero = 15;
const  iva = 21;
const Nombre;
const IVA;
Boolean

console.log("el inicio de la variable es: " + numero );
console.log('el inicio de la variable es:' + numero );
console.log('el inicio de la variable es: ${numero}');

// operadores Matematicos

/* let
var
const ; SE UTILIZA CON FUNCIONES.
son las tres manera de construir variables  */

numero = numero + 1;
console.log(numero);
